//! AI and Lua actions on Spreadsheet: generating agent context files,
//! Explain-with-AI, and capturing/previewing/applying AI-authored Lua.
//! Extracted from app.rs 2026-07-30 (pure move).

use gpui::*;

use crate::ai_cli::{detect_ai_cli, project_ai_context_template, system_ai_context, ALL_AI_CLIS};
use crate::settings::{update_user_settings, user_settings, TipId};
use crate::app::{count_lua_overwrites, extract_last_lua_block, save_ai_lua_script, sheet_fingerprint, Spreadsheet};

impl Spreadsheet {
    /// Generate AI context files for all supported CLIs.
    ///
    /// Creates two layers:
    /// - System: `~/.config/visigrid/ai/{CLAUDE.md, AGENTS.md, GEMINI.md}` (always)
    /// - Project: `<workbook_dir>/.visigrid/{CLAUDE.md, AGENTS.md, GEMINI.md}` (if saved)
    /// - Root stubs: `<workbook_dir>/{CLAUDE.md, AGENTS.md, GEMINI.md}` (if saved + writable)
    pub fn generate_ai_context_files(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        use std::fs;

        let mut created = Vec::new();
        let mut skipped = 0u32;
        let mut project_error: Option<String> = None;

        // 1. System-level files (always created, workbook-independent)
        let system_dir = Self::system_ai_config_dir();
        if let Err(e) = fs::create_dir_all(&system_dir) {
            self.status_message = Some(format!("Failed to create {}: {}", system_dir.display(), e));
            cx.notify();
            return;
        }
        let system_content = system_ai_context();
        for cli in ALL_AI_CLIS {
            let path = system_dir.join(cli.context_filename());
            if !path.exists() {
                if let Err(e) = fs::write(&path, system_content) {
                    log::warn!("Failed to write {}: {}", path.display(), e);
                } else {
                    created.push(format!("~/.config/visigrid/ai/{}", cli.context_filename()));
                }
            } else {
                skipped += 1;
            }
        }

        // 2. Project-level files (only if workbook is saved)
        if let Some(file_path) = &self.current_file.clone() {
            if let Some(workbook_dir) = file_path.parent() {
                let project_dir = workbook_dir.join(".visigrid");
                match fs::create_dir_all(&project_dir) {
                    Err(e) => {
                        crate::ai_metrics::record(crate::ai_metrics::AiMetricEvent::Error { category: "permission_denied" });
                        project_error = Some(format!(
                            "Cannot write project context in {}: {}. Use Save As to move the workbook.",
                            workbook_dir.display(), e
                        ));
                    }
                    Ok(()) => {
                        let wb_name = self.document_meta.display_name.clone();
                        let project_content = project_ai_context_template(&wb_name);
                        for cli in ALL_AI_CLIS {
                            let path = project_dir.join(cli.context_filename());
                            if !path.exists() {
                                if let Err(e) = fs::write(&path, &project_content) {
                                    log::warn!("Failed to write {}: {}", path.display(), e);
                                    if project_error.is_none() {
                                        project_error = Some(format!(
                                            "Cannot write to {}: {} (permission denied?)",
                                            project_dir.display(), e
                                        ));
                                    }
                                } else {
                                    created.push(format!(".visigrid/{}", cli.context_filename()));
                                }
                            } else {
                                skipped += 1;
                            }
                        }

                        // 3. Root stubs — tiny pointers so CLIs discover context at repo root
                        for cli in ALL_AI_CLIS {
                            let root_path = workbook_dir.join(cli.context_filename());
                            if !root_path.exists() {
                                let stub = format!(
                                    "<!-- This is a stub generated by VisiGrid. Edit .visigrid/{f} instead. -->\n\
                                     <!-- {name} reads this file for project context. -->\n\
                                     <!-- Do not put secrets here — this file may be committed to version control. -->\n\n\
                                     See [.visigrid/{f}](.visigrid/{f}) for project instructions.\n",
                                    f = cli.context_filename(),
                                    name = cli.display_name(),
                                );
                                if let Err(e) = fs::write(&root_path, &stub) {
                                    log::warn!("Failed to write root stub {}: {}", root_path.display(), e);
                                } else {
                                    created.push(cli.context_filename().to_string());
                                }
                            } else {
                                skipped += 1;
                            }
                        }
                    }
                }
            }
        } else {
            // Unsaved workbook: system files created, project files skipped with clear message
            project_error = Some(
                "Save the workbook first to create project-level context files.".into()
            );
        }

        // Build status message
        let mut msg = if !created.is_empty() {
            format!(
                "Created {}: {}",
                if created.len() == 1 { "1 file".to_string() } else { format!("{} files", created.len()) },
                created.join(", ")
            )
        } else if skipped > 0 {
            "AI context files already exist.".into()
        } else {
            String::new()
        };

        if let Some(err) = project_error {
            if !msg.is_empty() {
                msg.push_str(". ");
            }
            msg.push_str(&err);
        }

        if msg.is_empty() {
            msg = "No files created.".into();
        }

        self.status_message = Some(msg);
        cx.notify();
    }
    /// Open the project-level AI context folder in the system file manager.
    /// Falls back to the system-level folder if no workbook is saved.
    /// If the file manager can't open, copies path to clipboard as fallback.
    pub fn open_ai_context_folder(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        use std::fs;

        let folder = if let Some(file_path) = &self.current_file {
            if let Some(workbook_dir) = file_path.parent() {
                let project_dir = workbook_dir.join(".visigrid");
                if !project_dir.exists() {
                    let _ = fs::create_dir_all(&project_dir);
                }
                project_dir
            } else {
                Self::system_ai_config_dir()
            }
        } else {
            Self::system_ai_config_dir()
        };

        // Use platform file manager
        #[cfg(target_os = "linux")]
        let cmd = "xdg-open";
        #[cfg(target_os = "macos")]
        let cmd = "open";
        #[cfg(target_os = "windows")]
        let cmd = "explorer";

        match std::process::Command::new(cmd).arg(&folder).spawn() {
            Ok(_) => {
                self.status_message = Some(format!("Opened {}", folder.display()));
            }
            Err(_) => {
                crate::ai_metrics::record(crate::ai_metrics::AiMetricEvent::Error { category: "open_folder_failed" });
                // Fallback: copy path to clipboard
                let path_str = folder.display().to_string();
                cx.write_to_clipboard(gpui::ClipboardItem::new_string(path_str.clone()));
                self.status_message = Some(format!(
                    "Could not open file manager. Path copied to clipboard: {}", path_str
                ));
            }
        }
        cx.notify();
    }
    fn system_ai_config_dir() -> std::path::PathBuf {
        dirs::config_dir()
            .unwrap_or_else(|| std::path::PathBuf::from("."))
            .join("visigrid")
            .join("ai")
    }
    /// Open the AI metrics JSON file in the system file manager.
    /// Falls back to copying the path to clipboard if the file manager fails.
    pub fn open_ai_metrics(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        // Flush any buffered metrics first so the file is up to date
        crate::ai_metrics::flush();

        let path = crate::ai_metrics::metrics_path();
        if !path.exists() {
            self.status_message = Some("No AI metrics recorded yet.".into());
            cx.notify();
            return;
        }

        #[cfg(target_os = "linux")]
        let cmd = "xdg-open";
        #[cfg(target_os = "macos")]
        let cmd = "open";
        #[cfg(target_os = "windows")]
        let cmd = "explorer";

        match std::process::Command::new(cmd).arg(&path).spawn() {
            Ok(_) => {
                self.status_message = Some(format!("Opened {}", path.display()));
            }
            Err(_) => {
                let path_str = path.display().to_string();
                cx.write_to_clipboard(gpui::ClipboardItem::new_string(path_str.clone()));
                self.status_message = Some(format!(
                    "Could not open file. Path copied to clipboard: {}", path_str
                ));
            }
        }
        cx.notify();
    }
    /// Orchestration: launch AI CLI (if needed), paste full context, and append an analysis prompt.
    ///
    /// This is the "instant value" command — one keystroke from data to insight.
    pub fn ai_explain_selection(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        let pref = crate::settings::user_settings(cx).terminal.preferred_ai_cli;

        // Check if AI CLI is available before doing anything
        if detect_ai_cli(pref).is_none() {
            crate::ai_metrics::record(crate::ai_metrics::AiMetricEvent::Error { category: "no_cli" });
            self.status_message = Some(
                "No AI CLI found. Install one: npm i -g @anthropic-ai/claude-code | @openai/codex | @google/gemini-cli".into()
            );
            cx.notify();
            return;
        }

        // Check if we have a non-empty selection worth explaining
        let wb = self.workbook.read(cx);
        let sheet = wb.active_sheet();
        let ((top, left), (bottom, right)) = self.selection_range();
        let has_data = (top..=bottom).any(|r| {
            (left..=right).any(|c| !sheet.get_display(r, c).is_empty())
        });
        drop(wb);

        if !has_data {
            self.status_message = Some("Select cells with data first.".into());
            cx.notify();
            return;
        }

        crate::ai_metrics::record(crate::ai_metrics::AiMetricEvent::ExplainSelection);

        // Ensure AI is running in terminal (launches if not already)
        let ai_already_running = self.terminal.visible && self.terminal.term.is_some();
        if !ai_already_running {
            // Snapshot the output epoch before launch so we can detect new output
            let epoch_before = self.terminal.output_epoch();
            self.launch_ai_terminal(window, cx);
            // Wait for the CLI to produce output (detected via epoch change).
            // O(1) check — no grid lock. Timeout after 3s.
            let entity = cx.entity().downgrade();
            cx.spawn(async move |_, cx| {
                let start = std::time::Instant::now();
                let timeout = std::time::Duration::from_secs(3);
                let poll_interval = std::time::Duration::from_millis(100);

                loop {
                    smol::Timer::after(poll_interval).await;

                    let ready = entity.update(cx, |this: &mut Self, _cx| {
                        this.terminal.output_epoch() != epoch_before
                    }).unwrap_or(false);

                    if ready || start.elapsed() >= timeout {
                        break;
                    }
                }

                let _ = entity.update(cx, |this: &mut Self, cx| {
                    this.paste_full_context_with_prompt(cx);
                });
            }).detach();
        } else {
            // Terminal already running — paste immediately
            self.paste_full_context_with_prompt(cx);
        }
    }
    /// Write the AI context file (`.visigrid/CLAUDE.md`) with system context,
    /// sheet metadata, and optional extra instructions (e.g., Lua API contract).
    ///
    /// Returns the (sheet_name, headers, selection TSV) for the caller to paste
    /// into the terminal as visible user context.
    pub(crate) fn write_ai_context_and_collect_data(
        &mut self,
        cx: &mut Context<Self>,
        extra_instructions: &str,
    ) -> Option<(String, Vec<String>, String, usize, usize, usize, usize)> {
        let wb = self.workbook.read(cx);
        let sheet = wb.active_sheet();
        let sheet_name = sheet.name.clone();
        let (used_start_row, used_start_col, used_end_row, used_end_col) =
            crate::ai::find_used_range(sheet);

        // Detect headers
        let mut header_row = used_start_row;
        for r in used_start_row..(used_start_row + 20).min(used_end_row + 1) {
            let row_vals: Vec<String> = (used_start_col..=used_end_col)
                .map(|c| sheet.get_display(r, c))
                .collect();
            if crate::ai::looks_like_header_row(&row_vals) {
                header_row = r;
                break;
            }
        }
        let headers: Vec<String> = (used_start_col..=used_end_col)
            .map(|c| sheet.get_display(header_row, c))
            .filter(|s| !s.is_empty())
            .collect();

        // Selection TSV (capped)
        let ((top_row, left_col), (bottom_row, right_col)) = self.selection_range();
        let sel_rows = bottom_row - top_row + 1;
        let sel_cols = right_col - left_col + 1;
        let capped_rows = sel_rows.min(Self::PASTE_MAX_ROWS);
        let capped_cols = sel_cols.min(Self::PASTE_MAX_COLS);

        let mut lines = Vec::new();
        let mut total_chars = 0usize;
        for r in top_row..top_row + capped_rows {
            let mut cells = Vec::new();
            for c in left_col..left_col + capped_cols {
                cells.push(sheet.get_display(r, c));
            }
            let line = cells.join("\t");
            total_chars += line.len() + 1;
            if total_chars > Self::PASTE_MAX_CHARS {
                break;
            }
            lines.push(line);
        }
        drop(wb);

        let tsv = lines.join("\n");

        // Write .visigrid/CLAUDE.md with full context (instructions stay out of terminal)
        let workspace = self.terminal.workspace_root.clone()
            .or_else(|| self.current_file.as_ref().and_then(|p| p.parent().map(|d| d.to_path_buf())));
        if let Some(ref ws) = workspace {
            let visigrid_dir = ws.join(".visigrid");
            let _ = std::fs::create_dir_all(&visigrid_dir);
            let context_path = visigrid_dir.join("CLAUDE.md");

            let mut context = String::new();
            context.push_str(system_ai_context());
            context.push('\n');

            // Sheet metadata
            context.push_str("## Current Session\n\n");
            if let Some(p) = &self.current_file {
                context.push_str(&format!("- **File**: {}\n", p.display()));
            }
            context.push_str(&format!(
                "- **Sheet**: \"{}\"  Used range: {}x{}\n",
                sheet_name, used_end_row + 1, used_end_col + 1,
            ));
            if !headers.is_empty() {
                context.push_str(&format!(
                    "- **Headers** (row {}): {}\n",
                    header_row + 1, headers.join(", ")
                ));
            }
            context.push_str(&format!(
                "- **Selection**: {}x{} starting at {}\n",
                sel_rows, sel_cols, crate::ai::cell_ref(top_row, left_col),
            ));

            // Extra instructions (Lua contract, analysis hints, etc.)
            if !extra_instructions.is_empty() {
                context.push('\n');
                context.push_str(extra_instructions);
            }

            if let Err(e) = std::fs::write(&context_path, &context) {
                log::warn!("Failed to write AI context file {}: {}", context_path.display(), e);
            }
        }

        Some((sheet_name, headers, tsv, sel_rows, sel_cols, used_end_row, used_end_col))
    }
    /// Open the pending result as a sheet AND send it to the AI CLI for explanation.
    pub fn explain_structured_result(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        let pref = crate::settings::user_settings(cx).terminal.preferred_ai_cli;
        if detect_ai_cli(pref).is_none() {
            self.status_message = Some(
                "No AI CLI found. Install one: npm i -g @anthropic-ai/claude-code | @openai/codex | @google/gemini-cli".into()
            );
            cx.notify();
            return;
        }

        // Build explanation prompt from the pending result before consuming it.
        // Hard cap: 8000 chars to avoid blowing up the AI CLI.
        const EXPLAIN_MAX_CHARS: usize = 8000;
        const EXPLAIN_MAX_ROWS: usize = 20;

        let result = match self.terminal.pending_result {
            Some(crate::terminal::state::PendingResult::Structured(ref r)) => r,
            _ => return,
        };
        let description = result.description();
        let prompt = match result {
            crate::structured_results::StructuredResult::Diff { raw } => {
                let summary = raw.get("summary")
                    .map(|s| serde_json::to_string_pretty(s).unwrap_or_default())
                    .unwrap_or_default();
                let results = raw.get("results").and_then(|r| r.as_array());
                let n_results = results.map(|a| a.len()).unwrap_or(0);
                // Include first N diff rows as compact JSON
                let mut diff_sample = String::new();
                if let Some(rows) = results {
                    for row in rows.iter().take(EXPLAIN_MAX_ROWS) {
                        let line = serde_json::to_string(row).unwrap_or_default();
                        if diff_sample.len() + line.len() > EXPLAIN_MAX_CHARS / 2 { break; }
                        diff_sample.push_str(&line);
                        diff_sample.push('\n');
                    }
                    if n_results > EXPLAIN_MAX_ROWS {
                        diff_sample.push_str(&format!("# ... {} more changes\n", n_results - EXPLAIN_MAX_ROWS));
                    }
                }
                format!(
                    "# VisiGrid structured result: {}\n\
                     # Type: diff\n\
                     # Summary: {}\n\
                     # {} change(s) detected\n\n\
                     {}\n\
                     Explain this diff result. What changed and why might it matter? \
                     Are there anomalies or patterns worth investigating?\n",
                    description, summary.trim(), n_results, diff_sample
                )
            }
            crate::structured_results::StructuredResult::Peek { columns, rows } => {
                // Include column names + first N rows, capped by chars
                let mut tsv = columns.join("\t");
                tsv.push('\n');
                for row in rows.iter().take(EXPLAIN_MAX_ROWS) {
                    let cells: Vec<String> = row.iter()
                        .map(|v| crate::structured_results::json_cell_value_pub(v))
                        .collect();
                    let line = cells.join("\t");
                    if tsv.len() + line.len() > EXPLAIN_MAX_CHARS / 2 { break; }
                    tsv.push_str(&line);
                    tsv.push('\n');
                }
                if rows.len() > EXPLAIN_MAX_ROWS {
                    tsv.push_str(&format!("# ... {} more rows\n", rows.len() - EXPLAIN_MAX_ROWS));
                }
                format!(
                    "# VisiGrid structured result: {}\n\
                     # Type: peek ({} cols x {} rows)\n\n\
                     {}\n\
                     Summarize what this data shows. Detect anomalies, outliers, or patterns. \
                     Suggest formulas or next steps.\n",
                    description, columns.len(), rows.len(), tsv
                )
            }
            crate::structured_results::StructuredResult::Calc { value } => {
                let mut display = serde_json::to_string_pretty(value).unwrap_or_default();
                if display.len() > EXPLAIN_MAX_CHARS / 2 {
                    display.truncate(EXPLAIN_MAX_CHARS / 2);
                    display.push_str("\n# ... truncated");
                }
                format!(
                    "# VisiGrid structured result: {}\n\
                     # Type: calc\n\
                     # Value:\n{}\n\n\
                     Explain this calculation result. Is the value expected? \
                     What does it mean in context?\n",
                    description, display
                )
            }
        };

        // Open the result as a sheet
        self.open_structured_result_inner(cx);

        // Launch AI if not already running, then paste prompt
        let ai_already_running = self.terminal.visible && self.terminal.term.is_some();
        if !ai_already_running {
            let epoch_before = self.terminal.output_epoch();
            self.launch_ai_terminal(window, cx);
            let entity = cx.entity().downgrade();
            cx.spawn(async move |_, cx| {
                let start = std::time::Instant::now();
                let timeout = std::time::Duration::from_secs(3);
                let poll_interval = std::time::Duration::from_millis(100);
                loop {
                    smol::Timer::after(poll_interval).await;
                    let ready = entity.update(cx, |this: &mut Self, _cx| {
                        this.terminal.output_epoch() != epoch_before
                    }).unwrap_or(false);
                    if ready || start.elapsed() >= timeout { break; }
                }
                let _ = entity.update(cx, |this: &mut Self, cx| {
                    this.write_to_pty_bracketed(&prompt, cx);
                    this.status_message = Some("Sent result to AI for explanation.".into());
                    cx.notify();
                });
            }).detach();
        } else {
            self.write_to_pty_bracketed(&prompt, cx);
            self.status_message = Some("Sent result to AI for explanation.".into());
            cx.notify();
        }
    }
    /// Orchestrator: launch AI CLI, paste full VisiGrid context, and instruct
    /// the AI to output a Lua model in a fenced ```lua block.
    ///
    /// After the AI responds, the user runs "AI: Capture Last Lua Block" to preview.
    pub fn build_model_with_lua(&mut self, window: &mut Window, cx: &mut Context<Self>) {
        // Launch AI CLI (reuse existing logic — opens terminal, starts CLI)
        let pref = crate::settings::user_settings(cx).terminal.preferred_ai_cli;
        if detect_ai_cli(pref).is_none() {
            self.status_message = Some(
                "No AI CLI found. Install one: npm i -g @anthropic-ai/claude-code | @openai/codex | @google/gemini-cli".into()
            );
            cx.notify();
            return;
        }

        // Snapshot epoch before launch so we can detect when the CLI produces output.
        let epoch_before = self.terminal.output_epoch();
        let ai_already_running = self.terminal.visible && self.terminal.term.is_some();

        self.launch_ai_terminal(window, cx);

        if ai_already_running {
            // Terminal already running — paste context + contract immediately
            self.paste_lua_build_context(cx);
        } else {
            // Wait for output epoch bump (CLI boot), then paste. Timeout 3s.
            let entity = cx.entity().downgrade();
            cx.spawn(async move |_, cx| {
                let start = std::time::Instant::now();
                let timeout = std::time::Duration::from_secs(3);
                let poll_interval = std::time::Duration::from_millis(100);

                loop {
                    smol::Timer::after(poll_interval).await;
                    let ready = entity.update(cx, |this: &mut Self, _cx| {
                        this.terminal.output_epoch() != epoch_before
                    }).unwrap_or(false);
                    if ready || start.elapsed() >= timeout {
                        break;
                    }
                }

                let _ = entity.update(cx, |this: &mut Self, cx| {
                    this.paste_lua_build_context(cx);
                });
            }).detach();
        }

        crate::ai_metrics::record(crate::ai_metrics::AiMetricEvent::LaunchAi {
            cli: "build_model_lua",
        });
        self.status_message = Some(
            "Building Lua model… AI will output a ```lua block. Then run \"AI: Capture Last Lua Block\".".into()
        );
        cx.notify();
    }
    /// Paste VisiGrid context + Lua contract into the terminal.
    fn paste_lua_build_context(&mut self, cx: &mut Context<Self>) {
        if !self.terminal.visible || self.terminal.term.is_none() {
            return;
        }

        // Lua API contract + rules — written to .visigrid/CLAUDE.md, not pasted
        let lua_instructions = "\
## Task: Build Lua Model

Output ONLY a single ```lua fenced code block. No other text or code.

### VisiGrid Lua Sheet API (1-indexed)

```
sheet:set_value(row, col, value)
sheet:set_formula(row, col, \"=...\")
sheet:get_value(row, col)
sheet:rows()
sheet:cols()
```

### Rules

- Read inputs from the current sheet. Write outputs to new rows/columns.
- Do NOT delete or overwrite existing data.
- No `os`, `io`, file, or network operations.
- The user will preview your code before applying it.
";

        let Some((sheet_name, headers, tsv, sel_rows, sel_cols, ..)) =
            self.write_ai_context_and_collect_data(cx, lua_instructions)
        else {
            return;
        };

        // Paste a visible prompt (seen by the user AND sent to the AI CLI).
        // The Lua API contract and full instructions are in .visigrid/CLAUDE.md
        // which the AI CLI auto-discovers.
        let mut block = String::new();
        block.push_str(&format!(
            "# VisiGrid: Build Lua Model\n# Sheet: \"{}\" | Selection: {}x{}",
            sheet_name, sel_rows, sel_cols,
        ));
        if !headers.is_empty() {
            block.push_str(&format!(" | Headers: {}", headers.join(", ")));
        }
        block.push_str("\n# Lua API docs and rules are in .visigrid/CLAUDE.md\n");
        if !tsv.trim().is_empty() {
            block.push_str(&tsv);
            block.push('\n');
        }
        block.push_str("\nBuild a Lua model for this data. Output a single ```lua block.\n");

        // Write directly — not bracketed paste. The AI CLI is the foreground
        // process and doesn't interpret bracketed paste escapes (they'd show
        // as literal "200~" / "201~").
        self.terminal.write_to_pty(block.as_bytes());
    }
    /// Capture the last ` ```lua ` block from terminal scrollback, preview it, and
    /// store as a PendingResult::LuaPreview for the affordance bar.
    pub fn capture_ai_lua(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        use crate::terminal::state::{LuaPreviewData, PendingResult};
        use crate::scripting::SheetSnapshot;

        // Guard: terminal must be running
        let Some(ref term_arc) = self.terminal.term else {
            self.status_message = Some("No terminal session.".into());
            cx.notify();
            return;
        };

        // Extract recent terminal text
        let text = crate::terminal::extract::extract_recent_text(term_arc, 2000);

        // Find last ```lua block
        let Some(code) = extract_last_lua_block(&text) else {
            // Check if last.lua exists for a helpful hint
            let has_last = self.terminal.workspace_root.as_ref()
                .map(|r| r.join("ai").join("generated").join("last.lua").exists())
                .unwrap_or(false);
            let hint = if has_last {
                " Try \"AI: Preview last.lua\" to re-preview the previous script."
            } else {
                ""
            };
            self.status_message = Some(format!(
                "No ```lua block found. Make sure the AI outputs a ```lua fenced block.{}",
                hint
            ));
            cx.notify();
            return;
        };

        // Save script to disk
        let script_path = save_ai_lua_script(&code, &self.terminal.workspace_root);

        // Compute blake3 hash (first 16 bytes hex = 32 hex chars)
        let hash = blake3::hash(code.as_bytes());
        let script_hash = hash.to_hex()[..32].to_string();

        // Snapshot current sheet for preview
        let sheet = self.sheet(cx);
        let source_sheet_index = self.sheet_index(cx);
        let source_fingerprint = sheet_fingerprint(sheet);
        let snapshot = SheetSnapshot::from_sheet(sheet);

        // Run Lua in sandboxed preview mode (no mutation)
        let result = self.lua_runtime.eval_with_sheet(&code, Box::new(snapshot));

        // Count overwrites
        let cells_overwritten = self.workbook.read(cx).sheet(source_sheet_index)
            .map(|s| count_lua_overwrites(&result.ops, s))
            .unwrap_or(0);

        // Handle replace-pending: if there's already a pending result, toast
        if self.terminal.pending_result.is_some() {
            self.status_message = Some("Previous pending result replaced.".into());
        }

        // Run Log: record LuaPreview entry
        let source_sheet_name = self.workbook.read(cx)
            .sheet_names()
            .get(source_sheet_index)
            .map(|s| s.to_string())
            .unwrap_or_default();
        {
            let sp = script_path.clone();
            let sh = script_hash.clone();
            let writes = result.mutations;
            self.workbook.update(cx, |wb, _| {
                let meta = crate::structured_results::ResultMeta {
                    sheet_idx: source_sheet_index,
                    sheet_name: source_sheet_name,
                    result_type: "LuaPreview",
                    row_count: writes,
                    col_count: cells_overwritten,
                };
                crate::structured_results::append_run_log(
                    wb, &meta,
                    Some(sp.to_string_lossy().as_ref()),
                    Some(&sh),
                );
            });
        }

        // Store preview
        self.terminal.pending_result = Some(PendingResult::LuaPreview(LuaPreviewData {
            script_path,
            script_hash,
            cells_written: result.mutations,
            cells_overwritten,
            ops: result.ops,
            source_sheet_index,
            source_fingerprint,
            output: result.output,
            error: result.error,
        }));

        cx.notify();
    }
    /// Re-preview last.lua from disk — recovers a dismissed preview or re-runs
    /// the most recent AI-generated script.
    pub fn preview_last_lua(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        use crate::terminal::state::{LuaPreviewData, PendingResult};
        use crate::scripting::SheetSnapshot;

        let last_path = self.terminal.workspace_root.as_ref()
            .map(|r| r.join("ai").join("generated").join("last.lua"));

        let Some(path) = last_path else {
            self.status_message = Some("No workspace root — open or save a file first.".into());
            cx.notify();
            return;
        };

        let code = match std::fs::read_to_string(&path) {
            Ok(c) if !c.trim().is_empty() => c,
            _ => {
                self.status_message = Some("No last.lua found. Run \"AI: Capture Last Lua Block\" first.".into());
                cx.notify();
                return;
            }
        };

        // Same preview flow as capture_ai_lua but from file
        let hash = blake3::hash(code.as_bytes());
        let script_hash = hash.to_hex()[..32].to_string();

        let sheet = self.sheet(cx);
        let source_sheet_index = self.sheet_index(cx);
        let source_fingerprint = sheet_fingerprint(sheet);
        let snapshot = SheetSnapshot::from_sheet(sheet);

        let result = self.lua_runtime.eval_with_sheet(&code, Box::new(snapshot));

        let cells_overwritten = self.workbook.read(cx).sheet(source_sheet_index)
            .map(|s| count_lua_overwrites(&result.ops, s))
            .unwrap_or(0);

        if self.terminal.pending_result.is_some() {
            self.status_message = Some("Previous pending result replaced.".into());
        }

        self.terminal.pending_result = Some(PendingResult::LuaPreview(LuaPreviewData {
            script_path: path,
            script_hash,
            cells_written: result.mutations,
            cells_overwritten,
            ops: result.ops,
            source_sheet_index,
            source_fingerprint,
            output: result.output,
            error: result.error,
        }));

        cx.notify();
    }
    /// Apply the pending Lua preview to a new sheet.
    pub fn apply_lua_to_new_sheet(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        use crate::terminal::state::PendingResult;

        let preview = match self.terminal.pending_result.take() {
            Some(PendingResult::LuaPreview(data)) => data,
            other => {
                self.terminal.pending_result = other;
                return;
            }
        };

        // Refuse if preview had error
        if preview.error.is_some() {
            self.terminal.pending_result = Some(PendingResult::LuaPreview(preview));
            self.status_message = Some("Cannot apply: Lua script had errors.".into());
            cx.notify();
            return;
        }

        let hash_prefix = if preview.script_hash.len() >= 8 {
            &preview.script_hash[..8]
        } else {
            &preview.script_hash
        };
        let base_name = format!("AI Result - {}", hash_prefix);

        // Create new sheet and apply ops
        let (sheet_name, sheet_idx) = self.workbook.update(cx, |wb, _| {
            let name = crate::structured_results::unique_sheet_name(wb, &base_name);
            let idx = wb.add_sheet_named(&name).unwrap_or_else(|| wb.add_sheet());
            (name, idx)
        });

        let (changes, format_patches) = crate::views::lua_console::apply_lua_ops(
            self, sheet_idx, &preview.ops, cx,
        );

        // Record undo
        let has_values = !changes.is_empty();
        let has_formats = !format_patches.is_empty();
        if has_values && has_formats {
            use crate::history::{UndoAction, FormatActionKind};
            let group = UndoAction::Group {
                actions: vec![
                    UndoAction::Values { sheet_index: sheet_idx, changes },
                    UndoAction::Format {
                        sheet_index: sheet_idx,
                        patches: format_patches,
                        kind: FormatActionKind::CellStyle,
                        description: "AI Lua: set cell styles".into(),
                    },
                ],
                description: "AI Lua apply".into(),
            };
            self.history.record_action_with_provenance(group, None);
            self.is_modified = true;
        } else if has_values {
            self.history.record_batch(sheet_idx, changes);
            self.is_modified = true;
        } else if has_formats {
            self.history.record_format(
                sheet_idx,
                format_patches,
                crate::history::FormatActionKind::CellStyle,
                "AI Lua: set cell styles".into(),
            );
            self.is_modified = true;
        }

        // Switch to new sheet
        self.workbook.update(cx, |wb, _| { let _ = wb.set_active_sheet(sheet_idx); });

        // Append Run Log entry
        self.workbook.update(cx, |wb, _| {
            let meta = crate::structured_results::ResultMeta {
                sheet_idx,
                sheet_name: sheet_name.clone(),
                result_type: "LuaApply",
                row_count: preview.cells_written,
                col_count: 0,
            };
            crate::structured_results::append_run_log(
                wb, &meta,
                Some(preview.script_path.to_string_lossy().as_ref()),
                Some(&preview.script_hash),
            );
        });

        self.status_message = Some(format!(
            "Applied AI Lua to new sheet '{}'.", sheet_name
        ));
        cx.notify();
    }
    /// Apply the pending Lua preview to the current (source) sheet.
    pub fn apply_lua_to_current_sheet(&mut self, _window: &mut Window, cx: &mut Context<Self>) {
        use crate::terminal::state::PendingResult;

        let preview = match self.terminal.pending_result.take() {
            Some(PendingResult::LuaPreview(data)) => data,
            other => {
                self.terminal.pending_result = other;
                return;
            }
        };

        // Refuse if preview had error
        if preview.error.is_some() {
            self.terminal.pending_result = Some(PendingResult::LuaPreview(preview));
            self.status_message = Some("Cannot apply: Lua script had errors.".into());
            cx.notify();
            return;
        }

        // Drift check: recompute fingerprint and compare
        let current_fp = self.workbook.read(cx).sheet(preview.source_sheet_index)
            .map(|s| sheet_fingerprint(s))
            .unwrap_or(0);

        if current_fp != preview.source_fingerprint {
            // Drift detected — redirect to new sheet
            self.status_message = Some(
                "Sheet changed since preview. Applying to new sheet instead.".into()
            );
            // Re-store the preview and delegate to new-sheet path
            self.terminal.pending_result = Some(PendingResult::LuaPreview(preview));
            self.apply_lua_to_new_sheet(_window, cx);
            return;
        }

        let sheet_idx = preview.source_sheet_index;

        let (changes, format_patches) = crate::views::lua_console::apply_lua_ops(
            self, sheet_idx, &preview.ops, cx,
        );

        // Record undo
        let has_values = !changes.is_empty();
        let has_formats = !format_patches.is_empty();
        if has_values && has_formats {
            use crate::history::{UndoAction, FormatActionKind};
            let group = UndoAction::Group {
                actions: vec![
                    UndoAction::Values { sheet_index: sheet_idx, changes },
                    UndoAction::Format {
                        sheet_index: sheet_idx,
                        patches: format_patches,
                        kind: FormatActionKind::CellStyle,
                        description: "AI Lua: set cell styles".into(),
                    },
                ],
                description: "AI Lua apply".into(),
            };
            self.history.record_action_with_provenance(group, None);
            self.is_modified = true;
        } else if has_values {
            self.history.record_batch(sheet_idx, changes);
            self.is_modified = true;
        } else if has_formats {
            self.history.record_format(
                sheet_idx,
                format_patches,
                crate::history::FormatActionKind::CellStyle,
                "AI Lua: set cell styles".into(),
            );
            self.is_modified = true;
        }

        // Append Run Log entry
        let sheet_name = self.workbook.read(cx)
            .sheet_names()
            .get(sheet_idx)
            .map(|s| s.to_string())
            .unwrap_or_default();
        self.workbook.update(cx, |wb, _| {
            let meta = crate::structured_results::ResultMeta {
                sheet_idx,
                sheet_name: sheet_name.clone(),
                result_type: "LuaApply",
                row_count: preview.cells_written,
                col_count: 0,
            };
            crate::structured_results::append_run_log(
                wb, &meta,
                Some(preview.script_path.to_string_lossy().as_ref()),
                Some(&preview.script_hash),
            );
        });

        self.status_message = Some(format!(
            "Applied AI Lua to current sheet '{}'.", sheet_name
        ));
        cx.notify();
    }
    /// One-time hint: "AI: Explain Selection auto-pastes everything."
    /// Appended to the first paste status message, then dismissed.
    pub(crate) fn maybe_append_ai_paste_tip(&self, msg: &mut String, cx: &mut Context<Self>) {
        if !user_settings(cx).is_tip_dismissed(TipId::AiPasteShortcut) {
            msg.push_str(" Tip: \"AI: Explain Selection\" auto-pastes everything.");
            update_user_settings(cx, |s| s.dismiss_tip(TipId::AiPasteShortcut));
        }
    }
}
